# -*- mode: python ; coding: utf-8 -*-
# Windows 平台目录模式打包
# 使用方法: pyinstaller molvis.spec

import os
import sys

block_cipher = None
root_dir = os.path.dirname(SPEC)

a = Analysis(
    ['Main.py'],
    pathex=[root_dir],
    binaries=[],
    datas=[
        # 项目自身模块（目录模式确保源码被完整收集）
        ('original_programs', 'original_programs'),
        ('utils.py', '.'),
    ],
    hiddenimports=[
        # ---- 第三方核心库 ----
        # RDKit
        'rdkit',
        'rdkit.Chem',
        'rdkit.Chem.AllChem',
        'rdkit.Chem.BondType',
        'rdkit.RDLogger',
        'rdkit.Geometry',
        'rdkit.Chem.Draw',
        'rdkit.Chem.rdChemReactions',
        'rdkit.Chem.Draw.rdMolDraw2D',
        'rdkit.DataStructs',
        'rdkit.Chem.rdmolfiles',
        # NumPy
        'numpy',
        'numpy._core',
        'numpy._core._exceptions',
        'numpy._core._methods',
        'numpy._core._dtype',
        'numpy._core._dtype_ctypes',
        'numpy._core._internal',
        'numpy._core._add_newdocs',
        'numpy._core._add_newdocs_scalars',
        'numpy._core._asarray',
        'numpy._core._machar',
        'numpy._core._operand_flag_tests',
        'numpy._core._rational_tests',
        'numpy._core._simd',
        'numpy._core._string_helpers',
        'numpy._core._struct_ufunc_tests',
        'numpy._core._type_aliases',
        'numpy._core._ufunc_config',
        'numpy._core._umath_tests',
        'numpy._core.arrayprint',
        'numpy._core.cversions',
        'numpy._core.defchararray',
        'numpy._core.einsumfunc',
        'numpy._core.fromnumeric',
        'numpy._core.function_base',
        'numpy._core.getlimits',
        'numpy._core.memmap',
        'numpy._core.multiarray',
        'numpy._core.numeric',
        'numpy._core.numerictypes',
        'numpy._core.overrides',
        'numpy._core.printoptions',
        'numpy._core.records',
        'numpy._core.shape_base',
        'numpy._core.strings',
        'numpy._core.umath',
        'numpy._pyinstaller',
        'numpy._typing',
        'numpy._utils',
        'numpy.compat',
        'numpy.core',
        'numpy.fft',
        'numpy.lib',
        'numpy.linalg',
        'numpy.ma',
        'numpy.matrixlib',
        'numpy.polynomial',
        'numpy.random',
        'numpy.rec',
        'numpy.strings',
        'numpy.typing',
        # NetworkX
        'networkx',
        # Matplotlib
        'matplotlib',
        'matplotlib.pyplot',
        'matplotlib.backends',
        'matplotlib.backends.backend_qt5agg',
        'matplotlib.backends.backend_tkagg',
        'matplotlib.backend_bases',
        'matplotlib.gridspec',
        'matplotlib.cm',
        'mpl_toolkits',
        'mpl_toolkits.mplot3d',
        # PyQt5
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.sip',
        # PIL / CairoSVG
        'PIL',
        'PIL.Image',
        'PIL.ImageTk',
        'cairosvg',
        # ---- 项目模块 ----
        'original_programs',
        'original_programs.alkane_isomer_visualizer',
        'original_programs.alkene_visualizer',
        'original_programs.alkene',
        'original_programs.alkyne',
        'original_programs.alkenyl_generator',
        'original_programs.polyene_generator',
        'original_programs.multcycloalkane',
        'original_programs.multcyclomultalkane',
        'original_programs.cycloalkene_generator',
        'original_programs.cyclopolyene_generator',
        'original_programs.polyalkenyne',
        'utils',
        # ---- 标准库 ----
        'multiprocessing',
        'concurrent.futures',
        'itertools',
        'functools',
        'signal',
        'traceback',
        'warnings',
        'collections',
        'collections.defaultdict',
        'typing',
        'datetime',
        'pickle',
    ],
    hookspath=[],
    runtime_hooks=[os.path.join(root_dir, 'runtime_hook.py')],
    excludes=[
        'test', 'pytest', 'IPython', 'notebook', 'jupyter', 'sphinx', 'docutils',
        'PySide6', 'PyQt6', 'PySide2',
        'qtpy', 'zmq', 'sqlalchemy', 'tables', 'lxml',
        'tkinter', 'tkinter.filedialog', 'tkinter.scrolledtext',
        'MAYGEN', 'MolGen',
    ],
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='molvis',
    debug=False,
    strip=False,
    upx=True,
    console=True,
    icon=os.path.join(root_dir, 'icon.ico'),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='molvis',
)
